title: Pets Dashboard
views:
  - title: Pets
    path: pets
    icon: mdi:cat
    type: sections
    max_columns: 3
    sections:
      - type: grid
        column_span: 1
        cards:
          - type: custom:stack-in-card
            mode: vertical
            card_mod:
              style: |
                ha-card {
                  border-radius: 16px;
                  border: 1px solid var(--divider-color);
                  box-shadow: none;
                  padding: 12px;
                }
            cards:
              - type: heading
                heading: Arashi
                heading_style: title
                icon: mdi:cat
              - type: custom:mushroom-chips-card
                chips:
                  - type: entity
                    entity: number.arashi_weight
                    icon: mdi:scale
                    content_info: state
                  - type: entity
                    entity: sensor.arashi_last_use_duration
                    icon: mdi:timer
                    content_info: state
              - type: entities
                entities:
                  - entity: sensor.arashi_last_use_date
                    name: Last Toilet Visit
                  - entity: sensor.arashi_last_litter_used
                    name: Last Litter Used
                  - entity: sensor.arashi_last_weight_measurement
                    name: Last Weight
                  - entity: sensor.cat_feeder_1_average_eating_time
                    name: Avg Eating Time
      - type: grid
        column_span: 1
        cards:
          - type: custom:stack-in-card
            mode: vertical
            card_mod:
              style: |
                ha-card {
                  border-radius: 16px;
                  border: 1px solid var(--divider-color);
                  box-shadow: none;
                  padding: 12px;
                }
            cards:
              - type: heading
                heading: Litter Box
                heading_style: title
                icon: mdi:toilet
              - type: custom:mushroom-chips-card
                chips:
                  - type: entity
                    entity: sensor.arashi_s_toilet_1_state
                    icon: mdi:state-machine
                    content_info: state
                  - type: entity
                    entity: binary_sensor.arashi_s_toilet_1_toilet_occupied
                    icon: mdi:cat
                    content_info: none
                  - type: entity
                    entity: sensor.arashi_s_toilet_1_litter_level
                    icon: mdi:gauge
                    content_info: state
                  - type: entity
                    entity: binary_sensor.arashi_s_toilet_1_sand_lack
                    icon: mdi:alert
                    content_info: none
                  - type: entity
                    entity: binary_sensor.arashi_s_toilet_1_wastebin_filled
                    icon: mdi:trash-can
                    content_info: none
              - type: entities
                entities:
                  - entity: sensor.arashi_s_toilet_1_times_used
                    name: Times Used Today
                  - entity: sensor.arashi_s_toilet_1_litter_weight
                    name: Litter Weight
                  - entity: sensor.arashi_s_toilet_1_odor_eliminator_n50_left_days
                    name: Odor Eliminator Days Left
                  - entity: sensor.arashi_s_toilet_1_last_event
                    name: Last Event
              - type: horizontal-stack
                cards:
                  - type: button
                    entity: button.arashi_s_toilet_1_scoop
                    name: Scoop
                    icon: mdi:shovel
                    tap_action:
                      action: toggle
                  - type: button
                    entity: button.arashi_s_toilet_1_level_litter
                    name: Level
                    icon: mdi:arrow-expand-horizontal
                    tap_action:
                      action: toggle
                  - type: button
                    entity: button.arashi_s_toilet_1_dump_litter
                    name: Dump
                    icon: mdi:delete-empty
                    tap_action:
                      action: toggle
              - type: custom:mushroom-chips-card
                chips:
                  - type: template
                    entity: switch.arashi_s_toilet_1_auto_clean
                    icon: mdi:refresh-auto
                    icon_color: "{{ 'green' if is_state('switch.arashi_s_toilet_1_auto_clean', 'on') else 'grey' }}"
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
                  - type: template
                    entity: switch.arashi_s_toilet_1_ai_soft_stool_detection
                    icon: mdi:emoticon-poop
                    icon_color: "{{ 'amber' if is_state('switch.arashi_s_toilet_1_ai_soft_stool_detection', 'on') else 'grey' }}"
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
                  - type: template
                    entity: switch.arashi_s_toilet_1_do_not_disturb
                    icon: mdi:minus-circle
                    icon_color: "{{ 'red' if is_state('switch.arashi_s_toilet_1_do_not_disturb', 'on') else 'grey' }}"
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
                  - type: template
                    entity: switch.arashi_s_toilet_1_child_lock
                    icon: mdi:lock
                    icon_color: "{{ 'orange' if is_state('switch.arashi_s_toilet_1_child_lock', 'on') else 'grey' }}"
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
      - type: grid
        column_span: 1
        cards:
          - type: custom:stack-in-card
            mode: vertical
            card_mod:
              style: |
                ha-card {
                  border-radius: 16px;
                  border: 1px solid var(--divider-color);
                  box-shadow: none;
                  padding: 12px;
                }
            cards:
              - type: heading
                heading: Feeder
                heading_style: title
                icon: mdi:food-drumstick
              - type: custom:mushroom-chips-card
                chips:
                  - type: entity
                    entity: sensor.cat_feeder_1_device_status
                    icon: mdi:state-machine
                    content_info: state
                  - type: entity
                    entity: binary_sensor.cat_feeder_1_feeding
                    icon: mdi:food
                    content_info: none
                  - type: entity
                    entity: binary_sensor.cat_feeder_1_food_level
                    icon: mdi:food-apple
                    content_info: none
                  - type: entity
                    entity: sensor.cat_feeder_1_battery_level
                    icon: mdi:battery
                    content_info: state
              - type: picture-entity
                entity: image.cat_feeder_1_last_eat_event
                name: Last Eating Event
                show_state: false
                show_name: true
              - type: picture-entity
                entity: image.cat_feeder_1_dish_after
                name: Bowl (After Feeding)
                show_state: false
                show_name: true
              - type: horizontal-stack
                cards:
                  - type: button
                    name: 5g
                    icon: mdi:food-drumstick
                    tap_action:
                      action: call-service
                      service: text.set_value
                      target:
                        entity_id: text.cat_feeder_1_manual_feed
                      data:
                        value: "5"
                  - type: button
                    name: 10g
                    icon: mdi:food-drumstick
                    tap_action:
                      action: call-service
                      service: text.set_value
                      target:
                        entity_id: text.cat_feeder_1_manual_feed
                      data:
                        value: "10"
                  - type: button
                    name: 15g
                    icon: mdi:food-drumstick
                    tap_action:
                      action: call-service
                      service: text.set_value
                      target:
                        entity_id: text.cat_feeder_1_manual_feed
                      data:
                        value: "15"
                  - type: button
                    name: 20g
                    icon: mdi:food-drumstick
                    tap_action:
                      action: call-service
                      service: text.set_value
                      target:
                        entity_id: text.cat_feeder_1_manual_feed
                      data:
                        value: "20"
              - type: entities
                entities:
                  - entity: sensor.cat_feeder_1_times_eaten
                    name: Times Eaten Today
                  - entity: sensor.cat_feeder_1_total_dispensed
                    name: Total Dispensed
                  - entity: sensor.cat_feeder_1_desiccant_left_days
                    name: Desiccant Days Left
              - type: custom:mushroom-chips-card
                chips:
                  - type: template
                    entity: switch.cat_feeder_1_camera
                    icon: mdi:camera
                    icon_color: "{{ 'blue' if is_state('switch.cat_feeder_1_camera', 'on') else 'grey' }}"
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
                  - type: template
                    entity: switch.cat_feeder_1_pet_tracking
                    icon: mdi:motion-sensor
                    icon_color: "{{ 'cyan' if is_state('switch.cat_feeder_1_pet_tracking', 'on') else 'grey' }}"
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
                  - type: template
                    entity: switch.cat_feeder_1_night_vision
                    icon: mdi:weather-night
                    icon_color: "{{ 'purple' if is_state('switch.cat_feeder_1_night_vision', 'on') else 'grey' }}"
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
                  - type: template
                    entity: switch.cat_feeder_1_surplus_control
                    icon: mdi:bowl-mix
                    icon_color: "{{ 'teal' if is_state('switch.cat_feeder_1_surplus_control', 'on') else 'grey' }}"
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
                  - type: template
                    entity: switch.cat_feeder_1_child_lock
                    icon: mdi:lock
                    icon_color: "{{ 'orange' if is_state('switch.cat_feeder_1_child_lock', 'on') else 'grey' }}"
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
