alias: Bedtime Reminder
description: Play bedtime reminder with optional phone charging warnings
triggers:
  - trigger: time
    at: "22:25:00"
conditions: []
actions:
  - variables:
      core_message: It's almost time to sleep.
      yoshi_should_charge: "{{ states('binary_sensor.yoshi_should_charge')|bool }}"
      queen_should_charge: "{{ states('binary_sensor.queen_should_charge')|bool }}"
      battery_warnings: |-
        {% if yoshi_should_charge and queen_should_charge %}
          Yoshi and QP, you should charge your phones.
        {% elif yoshi_should_charge %}
          Yoshi, you should charge your phone
        {% elif queen_should_charge %}
          QP, you should charge your phone
        {% else %}
          ""
        {% endif %}
      final_message: "{{ (core_message + ' ' + battery_warnings).strip() }}"
  - action: tts.speak
    metadata: {}
    target:
      entity_id: tts.home_assistant_cloud
    data:
      cache: true
      media_player_entity_id: media_player.all_speakers
      message: "{{ final_message }}"
mode: single
