alias: Calendar Event Reminder
description: Play a reminder sound 5 minutes before any family calendar event
triggers:
  - entity_id: calendar.family
    event: start
    offset: "-00:05:00"
    trigger: calendar
conditions:
  - condition: or
    conditions:
      - condition: state
        entity_id: person.yoshi
        state:
          - home
      - condition: state
        entity_id: person.queen
        state:
          - home
actions:
  - action: tts.cloud_say
    metadata: {}
    data:
      cache: true
      entity_id: media_player.all_speakers
      message: It's almost time for {{ trigger.calendar_event.summary }}
mode: single
